# Generated by Django 4.1.1 on 2023-04-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Название'),
        ),
    ]
