# Generated by Django 4.1.1 on 2023-04-16 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_animals_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='name',
            new_name='name_type',
        ),
    ]
