# Generated by Django 4.1.1 on 2023-04-16 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_animals_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.type', verbose_name='Вид'),
        ),
    ]
